"""
Reporting Agent (Node 5)
========================
The final terminal node in the SOAR pipeline.

Consumes the entire AgentState and uses the local LLM (llama3.1:8b) to synthesize
a cohesive, Markdown-formatted executive summary, attack narrative, and execution report.
It replaces the static JSON reports previously generated by the Decision Engine.

After report generation, this node acts as the final persistence layer, saving 
the entire incident (along with the new Markdown report) to MongoDB.
"""

import logging
from datetime import datetime
from typing import Dict, Any

from langchain_core.prompts import ChatPromptTemplate
from langchain_community.chat_models import ChatOllama
from pydantic import BaseModel, Field

from .base_agent import BaseAgent
from ..workflows.state import AgentState
from ..tools.mongodb_helper import mongodb_helper

logger = logging.getLogger(__name__)


class ReportingAgent(BaseAgent):
    """Generates the final comprehensive post-incident Markdown report and saves to DB."""

    _PROMPT = """You are a Lead SOC Analyst and Incident Commander writing a final Executive Post-Incident Report for the CISO and Executive Board.
Your goal is to synthesize the raw telemetry, AI security decisions, and execution receipts into a clean, highly professional Markdown report. Accuracy, industry context, and professionalism are of utmost importance.

Here is the context of the incident:
---
INCIDENT ID: {incident_id}
DECISION: {decision} (Tier: {final_tier})
DECISION REASON: {decision_reason}

ALERT SUMMARY:
{alert_summary}

ATTACK STAGE: {attack_stage}
REASONING HYPOTHESES:
{hypotheses}

REMEDIATION PLAN PROPOSED:
{remediation_plan}

ACTIONS EXECUTED:
{actions_executed}
---

Write a comprehensive, highly accurate professional report using EXACTLY the following Markdown structure:

## Executive Summary
(Write 2-3 precise and authoritative sentences summarizing the threat, what assets were impacted, the organizational risk, and what the pipeline decided to do to neutralize it.)

## Attack Narrative & Threat Intelligence Context
(Write a chronological, formally structured story of the attack based on the alert summary, hypotheses, and ATT&CK stage. Explain the tactical mechanics of the breach and the adversary's objective using industry-standard terminology.)

## SOAR Execution Status & Remediation Receipts
(If the decision was AUTO_EXECUTE: State that the threat was neutralized. List the actions that were successfully executed in bullet points.)
(If the decision was MANUAL_REVIEW: State why the pipeline stopped (Decision Reason) and list the proposed remediation plan steps that the IR team must now formally execute.)

## Rollback & Safe Recovery Commands
(If any actions were AUTO-EXECUTED, provide the logically sound commands or steps to undo them in the event of a false positive. If nothing was executed, state "N/A - No actions executed.")
"""

    def __init__(self):
        super().__init__("Reporting Node")
        # Explicitly using llama3.1:8b as requested
        self.llm = ChatOllama(model="llama3.1:8b", temperature=0.1)
        self.prompt = ChatPromptTemplate.from_template(self._PROMPT)
        self.chain = self.prompt | self.llm

    async def execute(self, state: AgentState) -> AgentState:
        self.log_info("=== Reporting Agent ===")
        incident_id = state.get("incident_id", "unknown")

        try:
            # Extract context for the prompt
            report_ctx = self._build_context(state)
            
            self.log_info("Invoking Llama 3.1 8B for report synthesis...")
            response = await self.chain.ainvoke(report_ctx)
            
            # The resulting Markdown string
            final_report_md = response.content
            state["comprehensive_report"] = final_report_md
            self.log_info("Report generation successful.")

        except Exception as e:
            self.log_error(f"Failed to generate report: {e}")
            state.setdefault("errors", []).append(f"reporting_agent: {e}")
            state["comprehensive_report"] = f"## Report Generation Failed\n\nError: {e}"

        # ── Database Persistence ──────────────────────────────────────────────
        # This occurs at the absolute end of the graph (Node 5).
        # It overwrites/saves to the `incidents` collection.
        state["execution_ended"] = datetime.utcnow()
        try:
            doc = self._build_incident_doc(state)
            mongodb_helper.save_incident(doc)
            self.log_info("Saved final incident document to MongoDB.")
        except Exception as e:
            self.log_error(f"MongoDB save failed: {e}")
            state.setdefault("errors", []).append(f"reporting/mongo: {e}")

        return state

    def _build_context(self, state: AgentState) -> Dict[str, Any]:
        """Flatten the AgentState into the prompt variables."""
        inv_report = state.get("investigation_report", {})
        ml_out     = state.get("ml_outputs", {})
        
        return {
            "incident_id":      state.get("incident_id", "unknown"),
            "decision":         state.get("decision", "MANUAL_REVIEW"),
            "final_tier":       state.get("final_tier", "l2"),
            "decision_reason":  state.get("decision_reason", "No reason provided"),
            "alert_summary":    inv_report.get("alert_summary", "No summary available"),
            "attack_stage":     f"Stage {ml_out.get('attack_stage', {}).get('stage_number', '?')} - {ml_out.get('attack_stage', {}).get('predicted_stage', 'Unknown')}",
            "hypotheses":       self._format_list(inv_report.get("hypotheses", [])),
            "remediation_plan": self._format_plan(state.get("remediation_plan", [])),
            "actions_executed": self._format_executed(state.get("actions_executed", [])),
        }

    def _format_list(self, items: list) -> str:
        if not items: return "None"
        return "\n".join(f"- {i}" for i in items)

    def _format_plan(self, plan: list) -> str:
        if not plan: return "None"
        return "\n".join(f"- [{a.get('type')}] Target: {a.get('target')} (Risk: {a.get('risk_level')})" for a in plan)

    def _format_executed(self, actions: list) -> str:
        if not actions: return "None successfully executed."
        out = []
        for a in actions:
            status = a.get("execution_result", "unknown")
            out.append(f"- [{a.get('type')}] Target: {a.get('target')} | Status: {status}")
        return "\n".join(out)

    def _build_incident_doc(self, state: AgentState) -> Dict[str, Any]:
        """Format the massive document payload for the `incidents` collection."""
        return {
            "incident_id":          state.get("incident_id"),
            "priority":             state.get("priority"),
            "triage_score":         state.get("triage_score"),
            "decision":             state.get("decision"),
            "final_tier":           state.get("final_tier"),
            "decision_reason":      state.get("decision_reason"),
            "auto_execute_score":   state.get("auto_execute_score"),
            "comprehensive_report": state.get("comprehensive_report"),
            
            # Raw telemetry
            "alert":                state.get("alert"),
            "ml_outputs":           state.get("ml_outputs"),
            
            # Agent outputs
            "investigation_report": state.get("investigation_report"),
            "remediation_plan":     state.get("remediation_plan"),
            "actions_executed":     state.get("actions_executed", []),
            "audit_reports":        state.get("audit_reports", []),
            "errors":               state.get("errors", []),
            
            # Timestamps
            "execution_started":    state.get("execution_started"),
            "execution_ended":      state.get("execution_ended"),
            "status":               "closed" if state.get("decision") == "AUTO_EXECUTE" else "open",
        }
